# Note: Using MySQL syntax

CREATE TABLE Users (
    ID       INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(64),
    password VARCHAR(64),
    PRIMARY KEY(ID)
);

CREATE TABLE Instances (
    ID      INT NOT NULL AUTO_INCREMENT,
    INSTANCE_ID VARCHAR(32),
    USER_ID INT NOT NULL,
    AWS_INSTANCE_ID VARCHAR(64),
    STATUS  VARCHAR(16),
    PUBLIC_DNS VARCHAR(64),
    DB_NAME VARCHAR(64),
    DB_USER VARCHAR(64),
    ERROR   TEXT,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(INSTANCE_ID),
    UNIQUE(AWS_INSTANCE_ID),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);