# Note: Using MySQL syntax

CREATE TABLE Users (
    ID       INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(64),
    password VARCHAR(64),
    PRIMARY KEY(ID)
);

CREATE TABLE Instances (
    ID      INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    AWS_INSTANCE_ID VARCHAR(64) NOT NULL,
    UNIQUE(AWS_INSTANCE_ID),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);